CREATE DATABASE DBDESAFIO;

USE DBDESAFIO;

DROP TABLE ALUNO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    SOBRENOME VARCHAR(200) NOT NULL,
    MATRICULA INT NOT NULL,
    NIVEL VARCHAR(200) NOT NULL,
    NP1 DECIMAL(8,2) NOT NULL,
    NP2 DECIMAL(8,2) NOT NULL,
    NT1 DECIMAL(8,2) NOT NULL,
    NT2 DECIMAL(8,2) NOT NULL,
    PESOPROVA DECIMAL(8,2) NOT NULL, 
    PESOTRABALHO DECIMAL(8,2) NOT NULL,
    MEDIAFINAL DECIMAL(8,2) NOT NULL,
    SITUACAO VARCHAR(200) NOT NULL

);


